web/web/router.ex
defmodule Placebooru.Router do
  use Placebooru.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Placebooru.Authenticate, :anybody
    #plug :protect_from_forgery
  end

  pipeline :members_only do
    plug Placebooru.Authenticate, :registered
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Placebooru do
    pipe_through :browser

    get "/", PageController, :index
    get "/tag/all/:page", TagController, :all
    get "/tag/:id/:page/:name", TagController, :single
    get "/item/:id/:tags", ItemController, :view
    get "/activity/comments/:page", ActivityController, :comments
    get "/activity/tags/:page", ActivityController, :tags
    get "/activity/favs/:page", ActivityController, :favs_all
    get "/activity/favs/:user_id/:page", ActivityController, :favs
    post "/login", UserController, :login
    get "/logout", UserController, :logout
  end

  # Members only
  scope "/", Placebooru do
    pipe_through [:browser, :members_only]

    get "/item/upload", ItemController, :preupload
    post "/item/upload", ItemController, :upload
    post "/tag/:id/comment", TagController, :comment
    post "/item/:id/comment", ItemController, :comment
    post "/item/:id/tag", ItemController, :tag
  end

  scope "/api", Placebooru do
    pipe_through :api
    get "/api/find_tags", TagController, :list
    post "/api/add_post", ItemController, :upload
  end

end

web/web/views/layout_view.ex
defmodule Placebooru.LayoutView do
  use Placebooru.Web, :view

  def title do
    %{title: title} = Application.get_env(:placebooru, :branding, %{title: "Default title"})
    title
  end
end

web/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= title %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <% alert_info = get_flash(@conn, :info) %>
      <%= if (alert_info) do %>
      <p class="alert alert-info"><%= alert_info %></p>
      <% end %>

      <% alert_danger = get_flash(@conn, :error) %>
      <%= if (alert_danger) do %>
      <p class="alert alert-danger"><%= alert_danger %></p>
      <% end %>

      <div class="header">
        <% user = @conn.assigns.current_user %>
        <%= if user do %>
        Logged in as <%= user[:name] %> (<%= user[:id] %>).
        <a href="<%= user_path(@conn, :logout) %>">logout</a>
        <%= else %>
        <form class="login" method="POST" action="/login">
        <input type="text" name="name" placeholder="name">
        <input type="password" name="passwd" placeholder="password">
        <input type="submit" value="Login / Register">
        </form>
        <% end %>
        <!--
        <form method="POST" action="/">
          <input type="text" name="q">
          <input type="submit" value="Search">
        </form>
        -->
        <div class="menu">
          <a href="<%= tag_path(@conn, :all, 1) %>">Browse</a>
          <a href="<%= activity_path(@conn, :comments, 1) %>">Comments</a>
          <a href="<%= activity_path(@conn, :tags, 1) %>">Recently&nbsp;tagged</a>
          <a href="<%= activity_path(@conn, :favs_all, 1) %>">Users favorites</a>
          <%= if user do %>
          <a href="<%= activity_path(@conn, :favs, user[:id], 1) %>"><%= user[:name] %></a>
          <a href="<%= item_path(@conn, :preupload) %>">Add</a>
          <% end %>
        </div>
      </div>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>

web/web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>kyon.pl - reborn</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <% alert_info = get_flash(@conn, :info) %>
      <%= if (alert_info) do %>
      <p class="alert alert-info"><%= alert_info %></p>
      <% end %>

      <% alert_danger = get_flash(@conn, :error) %>
      <%= if (alert_danger) do %>
      <p class="alert alert-danger"><%= alert_danger %></p>
      <% end %>

      <div class="header">
        <% user = @conn.assigns.current_user %>
        <%= if user do %>
        Logged in as <%= user[:name] %> (<%= user[:id] %>).
        <a href="<%= user_path(@conn, :logout) %>">logout</a>
        <%= else %>
        <form class="login" method="POST" action="/login">
        <input type="text" name="name" placeholder="name">
        <input type="password" name="passwd" placeholder="password">
        <input type="submit" value="Login / Register">
        </form>
        <% end %>
        <!--
        <form method="POST" action="/">
          <input type="text" name="q">
          <input type="submit" value="Search">
        </form>
        -->
        <div class="menu">
          <a href="<%= tag_path(@conn, :all, 1) %>">Browse</a>
          <a href="<%= activity_path(@conn, :comments, 1) %>">Comments</a>
          <a href="<%= activity_path(@conn, :tags, 1) %>">Recently&nbsp;tagged</a>
          <a href="<%= activity_path(@conn, :favs_all, 1) %>">Users favorites</a>
          <%= if user do %>
          <a href="<%= activity_path(@conn, :favs, user[:id], 1) %>"><%= user[:name] %></a>
          <a href="<%= item_path(@conn, :preupload) %>">Add</a>
          <% end %>
        </div>
      </div>

      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>